### ISSUE TITLE
Orphaned white cards remain in the pool.

### ISSUE THREAD

**Issue by goodwid** [SeHarlan/hards-against-cumanity#42]
If a user submits a white card and the czar has not yet picked, and the user is booted from the game, that card remains in play.  Not sure if this is expected behavior or not, but it seemed fishy.

**Comment by SeHarlan** [comment]
Hmm, there should be code in play that removes "chosen" white cards on disconnect. I'll have to make sure the same thing happens when "the boot" is done manually.
Thank you!

**Comment by SeHarlan** [comment]
Should be fixed now!
